/* DOCUMENT */
-- sequence --
DROP SEQUENCE IF EXISTS DOCUMENT_SEQ;

CREATE SEQUENCE DOCUMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;

-- table --
DROP TABLE IF EXISTS DOCUMENT;

CREATE TABLE DOCUMENT (
    ID          BIGINT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    CONTENT     BLOB NOT NULL
);
